-- =============================================================================
-- Snowflake gold-layer DDL.
-- dbt creates these on first run; this file documents the production shape.
-- =============================================================================

USE SCHEMA FINSIGHT.GOLD;

CREATE OR REPLACE TABLE DIM_ASSET (
    ASSET_KEY        STRING       NOT NULL,
    ASSET_SYMBOL     STRING       NOT NULL,
    ASSET_NAME       STRING,
    ASSET_CLASS      STRING,
    SECTOR           STRING,
    EFFECTIVE_FROM   TIMESTAMP_NTZ NOT NULL,
    EFFECTIVE_TO     TIMESTAMP_NTZ,
    IS_CURRENT       NUMBER(1)    NOT NULL,
    CONSTRAINT PK_DIM_ASSET PRIMARY KEY (ASSET_KEY)
)
CLUSTER BY (ASSET_SYMBOL, EFFECTIVE_FROM);

CREATE OR REPLACE TABLE FCT_DAILY_MARKET_METRICS (
    ASSET_KEY               STRING       NOT NULL,
    ASSET_SYMBOL            STRING       NOT NULL,
    TRADE_DATE              DATE         NOT NULL,
    CLOSE_USD               NUMBER(28,8),
    VOLUME_USD              NUMBER(28,4),
    MARKET_CAP_USD          NUMBER(28,4),
    DAILY_RETURN_PCT        FLOAT,
    ROLLING_30D_VOLATILITY  FLOAT,
    ROLLING_30D_AVG_RETURN  FLOAT,
    ASSET_CLASS             STRING,
    _GOLD_TS                TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_FCT_DAILY_MARKET PRIMARY KEY (ASSET_KEY, TRADE_DATE)
)
CLUSTER BY (TRADE_DATE, ASSET_SYMBOL);

CREATE OR REPLACE TABLE FCT_CUSTOMER_TRANSACTION_SUMMARY (
    CUSTOMER_KEY         STRING NOT NULL,
    CUSTOMER_ID          STRING NOT NULL,
    TRANSACTION_DATE     DATE   NOT NULL,
    TXN_COUNT            NUMBER(20),
    GROSS_USD            NUMBER(28,4),
    FRAUD_USD            NUMBER(28,4),
    AVG_TICKET_USD       NUMBER(28,4),
    DISTINCT_MERCHANTS   NUMBER(20),
    DISTINCT_CATEGORIES  NUMBER(20),
    LAST_TRANSACTION_TS  TIMESTAMP_NTZ,
    _GOLD_TS             TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (TRANSACTION_DATE);

-- ---------- Meta tables ------------------------------------------------------

USE SCHEMA FINSIGHT.META;

CREATE TABLE IF NOT EXISTS INGESTION_WATERMARKS (
    SOURCE_NAME      STRING        NOT NULL,
    TARGET_TABLE     STRING        NOT NULL,
    WATERMARK_VALUE  TIMESTAMP_NTZ NOT NULL,
    UPDATED_AT       TIMESTAMP_NTZ NOT NULL,
    CONSTRAINT PK_WATERMARKS PRIMARY KEY (SOURCE_NAME, TARGET_TABLE)
);

CREATE TABLE IF NOT EXISTS DQ_RESULTS (
    RUN_ID         STRING        NOT NULL,
    DAG_ID         STRING,
    LAYER          STRING,
    DATASET        STRING,
    CHECK_NAME     STRING,
    STATUS         STRING,
    FAILURES       NUMBER,
    DETAIL         VARIANT,
    EXECUTED_AT    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
